version: '3'

services:
  frontend:
    # image: awesome/webapp
    build: frontend
    ports:
      - "3000:3000"
    # networks:
    #   - front-tier
    #   - back-tier
    # secrets:
    #   - server-certificate

  backend:
    # image: awesome/database
    build: .
    # volumes:
    #   - db-data:/etc/data
    # ports:
    #   - "8000:8000"
    # networks:
    #   - back-tier

# volumes:
#   db-data:
#     driver: flocker
#     driver_opts:
#       size: "10GiB"

# networks:
#   # The presence of these objects is sufficient to define them
#   front-tier: {}
#   back-tier: {}